;************************************************************************/
;* Primary Chip Names with Designators
;************************************************************************/
ANYCOP= 0
COP912C= 1	  ; Basic Family
COP820= 2
COP840= 3
COP880= 4
COP820CJ= 5
COP840CJ= 6
COP8620= 7
COP8640= 8
COP8720= 9
COP943= 10

COP888CF= 20	  ; Feature Family
COP888CG= 21
COP888CL= 22
COP888CS= 23
COP888EG= 24
COP888EK= 25
COP884CT= 26
COP888BC= 27
COP888EB= 28
COP888EW= 29
COP888FH= 30
COP888GD= 31
COP888GG= 32
COP888GW= 33
COP888HG= 34
